direction = input("Enter direction e.g. up: ")
emotion = input("Enter emotion e.g. crazy: ")
action = input("Enter action e.g. drive: ")

print("I'm going " + direction + " and this time I fear there's no one to save me")
print("This all or nothing really got a way of driving me " + emotion)
print("")
print("I need somebody to " + action + ".")
print("Somebody to know")
print("Somebody to have")
print("Somebody to hold")
print("It's easy to say")
print("But it's never the same")
print("I guess I kinda liked the way you numbed all the pain")
print("")
print("Now the day bleeds")
print("Into nightfall")
print("And you're not here")
print("To get me through it all")
print("I let my guard down")
print("And then you pulled the rug")
print("I was getting kinda used to being someone you loved")